# Generated by Django 5.1.1 on 2024-12-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='photo_path',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='title',
        ),
        migrations.AddField(
            model_name='incident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='street',
            field=models.CharField(max_length=200),
        ),
    ]
